name = "Cobblemon"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd878c014989e08dae13e082beea95c44dee306b09cc818bc261a26bdda59fc0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
