name = "Cobblemon"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d4ac8f851fe9a1a9819162525b6404d6b2a4f5d5cd2945fcc107396bbdfed59"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
